package main

//
// same as crash.go but doesn't actually crash.
//
// go build -buildmode=plugin nocrash.go
//

import (
	crand "crypto/rand"
	"math/big"
	"os"
	"sort"
	"strconv"
	"strings"

	"6.824/mr"
)

func maybeCrash() {
	max := big.NewInt(1000)
	rr, _ := crand.Int(crand.Reader, max)
	if false && rr.Int64() < 500 {
		// crash!
		os.Exit(1)
	}
}

// Map is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(filename string, contents string) []mr.KeyValue {
	maybeCrash()

	kva := []mr.KeyValue{}
	kva = append(kva, mr.KeyValue{Key: "a", Value: filename})
	kva = append(kva, mr.KeyValue{Key: "b", Value: strconv.Itoa(len(filename))})
	kva = append(kva, mr.KeyValue{Key: "c", Value: strconv.Itoa(len(contents))})
	kva = append(kva, mr.KeyValue{Key: "d", Value: "xyzzy"})
	return kva
}

// Reduce is called once for each key generated by the map tasks,
// with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	maybeCrash()

	// sort values to ensure deterministic output.
	vv := make([]string, len(values))
	copy(vv, values)
	sort.Strings(vv)

	val := strings.Join(vv, " ")
	return val
}
